In [2]:
import numpy as np

In [3]:
vector = np.array([3, 4, 17,65])

In [4]:
print(vector)

[ 3  4 17 65]


In [5]:
matrix = np.array([[2, 5, 15], [20, 50, 30], [39, 99, 45]])

In [6]:
print(matrix)

[[ 2  5 15]
 [20 50 30]
 [39 99 45]]


In [7]:
print(matrix.shape)

(3, 3)


In [61]:
world_alcohol = np.genfromtxt('world-alcohol.csv', delimiter=',', dtype="U75", skip_header=1)
print(type(world_alcohol))

<class 'numpy.ndarray'>


In [62]:
world_alcohol_dtype = world_alcohol.dtype
print(world_alcohol_dtype)

<U75


In [63]:
world_alcohol

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ...,
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

In [22]:
ivoire_1985 = world_alcohol[2,4]
second_country = world_alcohol[1,2]

In [24]:
ivoire_1985

'1.62'

In [26]:
countries = world_alcohol[:,2]
alcohol_consumption = world_alcohol[:,4]

In [28]:
alcohol_consumption

array(['0', '0.5', '1.62', ..., '2.54', '0', '5.15'], dtype='<U75')

In [32]:
first_two_colums= world_alcohol[:,0:2]
first_ten_years=world_alcohol[0:10,0]
first_ten_rows=world_alcohol[0:10,:]
first_twenty_region= world_alcohol[0:20, 1:3]

In [33]:
first_ten_rows

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ['1986', 'Americas', 'Colombia', 'Beer', '4.27'],
       ['1987', 'Americas', 'Saint Kitts and Nevis', 'Beer', '1.98'],
       ['1987', 'Americas', 'Guatemala', 'Other', '0'],
       ['1987', 'Africa', 'Mauritius', 'Wine', '0.13'],
       ['1985', 'Africa', 'Angola', 'Spirits', '0.39'],
       ['1986', 'Americas', 'Antigua and Barbuda', 'Spirits', '1.55'],
       ['1984', 'Africa', 'Nigeria', 'Other', '6.1']], dtype='<U75')

In [35]:
countries_canada = world_alcohol[:,2] == "Canada"
variable_year_1984 = world_alcohol[:,0] == "1984"

In [37]:
print(countries_canada)
print(variable_year_1984)

[False False False ... False False False]
[False False False ... False False False]


In [38]:
country_is_Algeria = world_alcohol[:,2]=="Algeria"
country_Algeria=world_alcohol[country_is_Algeria,:]

In [39]:
print(country_Algeria)

[['1984' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1987' 'Africa' 'Algeria' 'Beer' '0.17']
 ['1987' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1986' 'Africa' 'Algeria' 'Wine' '0.1']
 ['1984' 'Africa' 'Algeria' 'Other' '0']
 ['1989' 'Africa' 'Algeria' 'Beer' '0.16']
 ['1989' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1989' 'Africa' 'Algeria' 'Wine' '0.23']
 ['1986' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1984' 'Africa' 'Algeria' 'Wine' '0.12']
 ['1985' 'Africa' 'Algeria' 'Beer' '0.19']
 ['1985' 'Africa' 'Algeria' 'Other' '0']
 ['1986' 'Africa' 'Algeria' 'Beer' '0.18']
 ['1985' 'Africa' 'Algeria' 'Wine' '0.11']
 ['1986' 'Africa' 'Algeria' 'Other' '0']
 ['1989' 'Africa' 'Algeria' 'Other' '0']
 ['1987' 'Africa' 'Algeria' 'Other' '0']
 ['1984' 'Africa' 'Algeria' 'Beer' '0.2']
 ['1985' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1987' 'Africa' 'Algeria' 'Wine' '0.1']]


In [43]:
years_1984=world_alcohol[(world_alcohol[:,0]=='1984'),:]

In [44]:
print(years_1984)

[['1984' 'Africa' 'Nigeria' 'Other' '6.1']
 ['1984' 'Eastern Mediterranean' 'Afghanistan' 'Other' '0']
 ['1984' 'Americas' 'Costa Rica' 'Wine' '0.06']
 ...
 ['1984' 'Europe' 'Latvia' 'Spirits' '7.5']
 ['1984' 'Africa' 'Angola' 'Wine' '0.57']
 ['1984' 'Africa' 'Central African Republic' 'Wine' '0.46']]


In [52]:
algeria_in_1986 = (world_alcohol[:,0]=='1986') & ((world_alcohol[:,2] == 'Algeria') | (world_alcohol[:,2] =='Colombia'))
row_algeria_in_1986 = world_alcohol[algeria_in_1986,:]
print(row_algeria_in_1986)

[['1986' 'Americas' 'Colombia' 'Beer' '4.27']
 ['1986' 'Africa' 'Algeria' 'Wine' '0.1']
 ['1986' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1986' 'Americas' 'Colombia' 'Wine' '0.15']
 ['1986' 'Americas' 'Colombia' 'Spirits' '2.19']
 ['1986' 'Africa' 'Algeria' 'Beer' '0.18']
 ['1986' 'Africa' 'Algeria' 'Other' '0']
 ['1986' 'Americas' 'Colombia' 'Other' '0']]


In [64]:
world_alcohol_2 = world_alcohol
value_1986 = world_alcohol_2[:,0] == '1986'
value_wine = world_alcohol_2[:,3] == 'Wine'
world_alcohol_2[:,0][value_1986]= '2018'
world_alcohol_2[:,3][value_wine] = 'Beer'

In [65]:
world_alcohol_2

array([['2018', 'Western Pacific', 'Viet Nam', 'Beer', '0'],
       ['2018', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Beer', '1.62'],
       ...,
       ['2018', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['2018', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

In [67]:
world_alcohol[:,4][world_alcohol[:,4] == ''] = '0'

In [69]:
alcohol_consumption = world_alcohol[:,4]
alcohol_consumption.astype(float)

array([0.  , 0.5 , 1.62, ..., 2.54, 0.  , 5.15])