In [2]:
import numpy as np

In [3]:
vector = np.array([3, 4, 17,65])

In [4]:
print(vector)

[ 3  4 17 65]


In [5]:
matrix = np.array([[2, 5, 15], [20, 50, 30], [39, 99, 45]])

In [6]:
print(matrix)

[[ 2  5 15]
 [20 50 30]
 [39 99 45]]


In [7]:
print(matrix.shape)

(3, 3)


In [11]:
world_alcohol = np.genfromtxt('world-alcohol.csv', delimiter=',')
print(type(world_alcohol))

<class 'numpy.ndarray'>
